import 'package:isar/isar.dart';

// This file will be generated by Isar in the next step
part 'clipboard_item.g.dart';

@collection
class ClipboardItem {
  Id id = Isar.autoIncrement; // Isar requires an integer ID

  @Index(
    type: IndexType.hash,
  ) // Makes searching for exact duplicates instantaneous
  late String content;

  late DateTime timestamp;
}
